USE test;

DROP TABLE IF EXISTS USER;

CREATE TABLE IF NOT EXISTS USER (
    IDUSER MEDIUMINT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (IDUSER)
);


INSERT INTO USER (USERNAME ) VALUES ('admin@gmail.com');
INSERT INTO USER (USERNAME) VALUES ('admin@gmail.com');
INSERT INTO USER (USERNAME) VALUES ('admin@gmail.com');
INSERT INTO USER (USERNAME) VALUES ('admin@gmail.com');
INSERT INTO USER (USERNAME) VALUES ('admin@gmail.com');
INSERT INTO USER (USERNAME) VALUES ('admin@gmail.com');



